language: cpp
compiler:
  - gcc
  - clang
script: ./configure && make && make check
install: sudo apt-get install llvm-dev libelf-dev libreadline-dev

matrix:
  include:
    - script: mkdir build/ && cd build/ && cmake .. && make && make test
      compiler: gcc
    - script: mkdir build/ && cd build/ && cmake .. && make && make test
      compiler: clang
